steps:
  # Step 1: Use an official Node.js image
  - name: 'node:20'
    id: 'Install Node.js'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g npm  # Upgrade npm to the latest version

  # Step 2: Install dependencies
  - name: 'node:20'
    id: 'npm install'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install'

  # Step 3: Build the Node.js application
  - name: 'node:20'
    id: 'npm build'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm run build'
      
  # Step 4: Copy project files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/src /workspace/public
        cp -r src/* /workspace/src
        cp -r public/* /workspace/public

  # Step 5: Publish npm artifact
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r /workspace/* gs://artifacts.prismatic-night-406207.appspot.com

artifacts:
  objects:
    location: 'gs://artifacts.prismatic-night-406207.appspot.com'
    paths:
      - '**'
